// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission90.Dal.Contexts;

#nullable disable

namespace Mission90.Dal.Migrations
{
    [DbContext(typeof(Mission90Context))]
    [Migration("20250403122158_third")]
    partial class third
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mission90.Dal.Models.Category", b =>
                {
                    b.Property<int>("Category_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Category_Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Category_Name");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.HasKey("Category_Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Category_Id = 1,
                            CategoryName = "test1",
                            DisplayOrder = 1
                        },
                        new
                        {
                            Category_Id = 2,
                            CategoryName = "test2",
                            DisplayOrder = 2
                        },
                        new
                        {
                            Category_Id = 3,
                            CategoryName = "test3",
                            DisplayOrder = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
